//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Football_Score
    {
        public int GameID { get; set; }
        public System.DateTime GameDate { get; set; }
        public string TeamNameOne { get; set; }
        public string TeamNameTwo { get; set; }
        public int PointsScoredTeamOne { get; set; }
        public int PointsScoredTeamTwo { get; set; }
        public int PointsAllowedTeamOne { get; set; }
        public int PointsAllowedTeamTwo { get; set; }
        public int Spectators { get; set; }
    }
}
