//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project01.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportScores : DbContext
    {
        public SportScores()
            : base("name=SportScores")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Football_Score> Football_Scores { get; set; }
        public virtual DbSet<Hockey_Score> Hockey_Scores { get; set; }
        public virtual DbSet<lacrosse_Score> lacrosse_Scores { get; set; }
        public virtual DbSet<Soccer_Score> Soccer_Scores { get; set; }
    }
}
