//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int Id { get; set; }
        public string SportName { get; set; }
        public string TeamNameOne { get; set; }
        public string TeamNameTwo { get; set; }
        public string Spectators { get; set; }
        public string PointsScoredTeamOne { get; set; }
        public string PointsScoredTeamTwo { get; set; }
    }
}
